[0m12:37:10.095604 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B883068B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B8868BD040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B8868BE960>]}


============================== 12:37:10.097619 | afe401e0-d738-42b3-be81-0595a757aff8 ==============================
[0m12:37:10.097619 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:37:10.102415 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\etienne.gelfi\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'c:\\DBT\\Projets\\snfk-dbt\\DPERFMGT\\logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:37:10.290303 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'afe401e0-d738-42b3-be81-0595a757aff8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B8869852B0>]}
[0m12:37:10.321788 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:37:10.323703 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:37:10.324747 [debug] [MainThread]: Command `cli deps` succeeded at 12:37:10.324747 after 0.54 seconds
[0m12:37:10.325704 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B886952CF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B886953B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B88613CF80>]}
[0m12:37:10.326348 [debug] [MainThread]: Flushing usage events
[0m12:37:10.690450 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:40:19.418802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024820D7B350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024823A98980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000248239090A0>]}


============================== 12:40:19.424802 | 9eb92754-25d9-4ead-8f69-ce013b649d8b ==============================
[0m12:40:19.424802 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:40:19.425103 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'c:\\DBT\\Projets\\snfk-dbt\\DPERFMGT\\logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\etienne.gelfi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt ', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:40:19.579569 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '9eb92754-25d9-4ead-8f69-ce013b649d8b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002482390BDD0>]}
[0m12:40:19.597097 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:40:19.608069 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:40:19.610356 [debug] [MainThread]: Command `cli deps` succeeded at 12:40:19.609359 after 0.46 seconds
[0m12:40:19.610356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024823A666F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024822FB5F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000248253CBF80>]}
[0m12:40:19.611410 [debug] [MainThread]: Flushing usage events
[0m12:40:19.967256 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:41:22.981723 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B98CE9B890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B98AA435F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B98AD08E60>]}


============================== 12:41:22.990622 | 84f928ff-ba46-4d79-abb5-595e224390a8 ==============================
[0m12:41:22.990622 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:41:22.991627 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\etienne.gelfi\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:41:22.992625 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\DBT\Projets\snfk-dbt\DPERFMGT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:41:22.994440 [debug] [MainThread]: Command `cli deps` failed at 12:41:22.993626 after 0.44 seconds
[0m12:41:22.995057 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B98D72CBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B98D9DFC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B98D9DFD10>]}
[0m12:41:22.996228 [debug] [MainThread]: Flushing usage events
[0m12:41:23.394112 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:41:25.245010 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025C2BAC94F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025C2BACBDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025C2BAC8860>]}


============================== 12:41:25.254025 | 220132f5-e57e-4a58-b21d-b128fc67583d ==============================
[0m12:41:25.254025 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:41:25.255071 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\etienne.gelfi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:41:25.256616 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\DBT\Projets\snfk-dbt\DPERFMGT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:41:25.257663 [debug] [MainThread]: Command `cli deps` failed at 12:41:25.257663 after 0.42 seconds
[0m12:41:25.258641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025C2A188C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025C29A5DC40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025C2C63F8C0>]}
[0m12:41:25.259302 [debug] [MainThread]: Flushing usage events
[0m12:41:25.359232 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:41:34.972667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272645FD7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272680CEB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027267C964B0>]}


============================== 12:41:34.983234 | 56fb374d-1381-400f-88b0-96b8df31533a ==============================
[0m12:41:34.983234 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:41:34.984753 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\etienne.gelfi\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'c:\\DBT\\Projets\\snfk-dbt\\logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:41:35.447507 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '56fb374d-1381-400f-88b0-96b8df31533a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272693E8320>]}
[0m12:41:35.519504 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:41:35.519504 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:41:35.527582 [debug] [MainThread]: Command `cli deps` succeeded at 12:41:35.527582 after 1.12 seconds
[0m12:41:35.529832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027267EFAE40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272694F15E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027267C964B0>]}
[0m12:41:35.529832 [debug] [MainThread]: Flushing usage events
[0m12:41:35.617401 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:43:29.865327 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9336555E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9336556D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B93369B500>]}


============================== 12:43:29.882506 | 49d6aacc-1ad3-4225-a700-50b0cb7b43ba ==============================
[0m12:43:29.882506 [info ] [MainThread]: Running with dbt=1.9.0
[0m12:43:29.883508 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'c:\\DBT\\Projets\\snfk-dbt\\logs', 'profiles_dir': 'C:\\Users\\etienne.gelfi\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt ', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:43:30.041464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '49d6aacc-1ad3-4225-a700-50b0cb7b43ba', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9313444A0>]}
[0m12:43:30.064137 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:43:30.064137 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m12:43:30.064137 [debug] [MainThread]: Command `cli deps` succeeded at 12:43:30.064137 after 0.49 seconds
[0m12:43:30.064137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B933CF8CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B9313444A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B93429E810>]}
[0m12:43:30.064137 [debug] [MainThread]: Flushing usage events
[0m12:43:30.419238 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:56:07.159996 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F213E97620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F214B9A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2150C7D90>]}


============================== 16:56:07.164799 | df7647d3-ed94-41d7-8b4b-8c93f5a3959f ==============================
[0m16:56:07.164799 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:56:07.166656 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:56:07.542527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'df7647d3-ed94-41d7-8b4b-8c93f5a3959f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F21459AFD0>]}
[0m16:56:07.584154 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'df7647d3-ed94-41d7-8b4b-8c93f5a3959f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2170018C0>]}
[0m16:56:07.585254 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m16:56:07.786721 [debug] [MainThread]: checksum: 2c026f85d539c10c69b093157526ce33d0bf5533489eafb07fe5172434ec7740, vars: {}, profile: , target: , version: 1.10.1
[0m16:56:07.968960 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m16:56:07.969339 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m16:56:07.992986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'df7647d3-ed94-41d7-8b4b-8c93f5a3959f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F217488B50>]}
[0m16:56:08.038153 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\manifest.json
[0m16:56:08.042331 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\semantic_manifest.json
[0m16:56:08.061838 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'df7647d3-ed94-41d7-8b4b-8c93f5a3959f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F213E9BA70>]}
[0m16:56:08.062354 [info ] [MainThread]: Found 2 models, 477 macros
[0m16:56:08.062969 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'df7647d3-ed94-41d7-8b4b-8c93f5a3959f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2170A9FD0>]}
[0m16:56:08.064465 [info ] [MainThread]: 
[0m16:56:08.065198 [info ] [MainThread]: Concurrency: 200 threads (target='dev')
[0m16:56:08.065726 [info ] [MainThread]: 
[0m16:56:08.066376 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m16:56:08.070915 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:56:08.082570 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:56:08.165953 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:56:08.166296 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:56:08.166545 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:56:08.167064 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:56:08.167487 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:56:08.167890 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:56:08.796784 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.629 seconds
[0m16:56:08.843172 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.676 seconds
[0m16:56:08.848460 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPERFMGT)
[0m16:56:08.849106 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPERFMGT"
"
[0m16:56:08.854902 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPERFMGT"
[0m16:56:08.855521 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPERFMGT: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPERFMGT"} */
create schema if not exists EXPOSE_DEV.dpulse_DPERFMGT
[0m16:56:08.856442 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPULSE)
[0m16:56:08.857019 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPULSE"
"
[0m16:56:08.858855 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPULSE"
[0m16:56:08.859510 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPULSE: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPULSE"} */
create schema if not exists EXPOSE_DEV.dpulse_DPULSE
[0m16:56:08.930602 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d20-0106-9fbc-0000-03a97fbbd0de
[0m16:56:08.930963 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:56:08.931412 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:56:08.931678 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:56:09.010901 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d20-0106-a02b-0000-03a97fbbbfb2
[0m16:56:09.011318 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:56:09.011661 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:56:09.011873 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:56:09.012778 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:56:09.013200 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPULSE' was left open.
[0m16:56:09.013557 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPULSE: Close
[0m16:56:09.083520 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPERFMGT' was left open.
[0m16:56:09.084408 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPERFMGT: Close
[0m16:56:09.160459 [info ] [MainThread]: 
[0m16:56:09.161121 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.09 seconds (1.09s).
[0m16:56:09.161936 [error] [MainThread]: Encountered an error:
Database Error
  003001 (42501): Erreur de contrôle d'accès SQL :
  privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:56:09.163544 [debug] [MainThread]: Command `dbt run` failed at 16:56:09.163335 after 2.24 seconds
[0m16:56:09.164190 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2176DA5B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F214EA3D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F217836090>]}
[0m16:56:09.164796 [debug] [MainThread]: Flushing usage events
[0m16:56:09.257712 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:57:43.544379 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019753957620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001975465A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019754B87D90>]}


============================== 16:57:43.548486 | 78f92751-42bb-43ef-a26b-1d84b026b705 ==============================
[0m16:57:43.548486 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:57:43.549741 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:57:43.926894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '78f92751-42bb-43ef-a26b-1d84b026b705', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001975405AFD0>]}
[0m16:57:43.969359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '78f92751-42bb-43ef-a26b-1d84b026b705', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019756B918C0>]}
[0m16:57:43.970456 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m16:57:44.153462 [debug] [MainThread]: checksum: 2c026f85d539c10c69b093157526ce33d0bf5533489eafb07fe5172434ec7740, vars: {}, profile: , target: , version: 1.10.1
[0m16:57:44.337864 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m16:57:44.338230 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m16:57:44.362243 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '78f92751-42bb-43ef-a26b-1d84b026b705', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001975701CB50>]}
[0m16:57:44.407978 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\manifest.json
[0m16:57:44.411778 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\semantic_manifest.json
[0m16:57:44.429660 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '78f92751-42bb-43ef-a26b-1d84b026b705', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001975395BA70>]}
[0m16:57:44.430060 [info ] [MainThread]: Found 2 models, 477 macros
[0m16:57:44.430806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '78f92751-42bb-43ef-a26b-1d84b026b705', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019756C39FD0>]}
[0m16:57:44.431999 [info ] [MainThread]: 
[0m16:57:44.432690 [info ] [MainThread]: Concurrency: 200 threads (target='dev')
[0m16:57:44.433369 [info ] [MainThread]: 
[0m16:57:44.434030 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m16:57:44.437509 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:57:44.449819 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:57:44.524776 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:57:44.525175 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:57:44.525425 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:57:44.526029 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:57:44.526309 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:57:44.526534 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:57:45.144944 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.618 seconds
[0m16:57:45.147140 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.622 seconds
[0m16:57:45.155887 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPERFMGT)
[0m16:57:45.156540 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPERFMGT"
"
[0m16:57:45.161996 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPERFMGT"
[0m16:57:45.162476 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPULSE)
[0m16:57:45.163019 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPERFMGT: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPERFMGT"} */
create schema if not exists EXPOSE_DEV.dpulse_DPERFMGT
[0m16:57:45.163585 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPULSE"
"
[0m16:57:45.165479 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPULSE"
[0m16:57:45.165801 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPULSE: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPULSE"} */
create schema if not exists EXPOSE_DEV.dpulse_DPULSE
[0m16:57:45.249074 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d21-0106-9fbc-0000-03a97fbbd23a
[0m16:57:45.249645 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:57:45.250134 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:57:45.250430 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:57:45.257779 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d21-0106-a02b-0000-03a97fbbe13a
[0m16:57:45.258265 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:57:45.258692 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:57:45.258979 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:57:45.259810 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:57:45.260101 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPERFMGT' was left open.
[0m16:57:45.260354 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPERFMGT: Close
[0m16:57:45.373066 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPULSE' was left open.
[0m16:57:45.373870 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPULSE: Close
[0m16:57:45.559416 [info ] [MainThread]: 
[0m16:57:45.560048 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.13 seconds (1.13s).
[0m16:57:45.560765 [error] [MainThread]: Encountered an error:
Database Error
  003001 (42501): Erreur de contrôle d'accès SQL :
  privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:57:45.561767 [debug] [MainThread]: Command `dbt run` failed at 16:57:45.561605 after 2.29 seconds
[0m16:57:45.562261 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001975756E820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019754963D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197573C6090>]}
[0m16:57:45.562737 [debug] [MainThread]: Flushing usage events
[0m16:57:45.886935 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:57:57.261271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015DFFC37620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D819CA490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D81EF7D90>]}


============================== 16:57:57.266786 | bca05128-54c3-441f-8c80-afbdd76eeaf9 ==============================
[0m16:57:57.266786 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:57:57.267590 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:57:57.661892 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'bca05128-54c3-441f-8c80-afbdd76eeaf9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D813DAFD0>]}
[0m16:57:57.708001 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'bca05128-54c3-441f-8c80-afbdd76eeaf9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D83E318C0>]}
[0m16:57:57.709282 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m16:57:57.894122 [debug] [MainThread]: checksum: 2c026f85d539c10c69b093157526ce33d0bf5533489eafb07fe5172434ec7740, vars: {}, profile: , target: , version: 1.10.1
[0m16:57:58.059030 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m16:57:58.059376 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m16:57:58.085126 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'bca05128-54c3-441f-8c80-afbdd76eeaf9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D842B8B50>]}
[0m16:57:58.129469 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\manifest.json
[0m16:57:58.133476 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\semantic_manifest.json
[0m16:57:58.151814 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'bca05128-54c3-441f-8c80-afbdd76eeaf9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015DFFC3BA70>]}
[0m16:57:58.152235 [info ] [MainThread]: Found 2 models, 477 macros
[0m16:57:58.152981 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'bca05128-54c3-441f-8c80-afbdd76eeaf9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D83ED9FD0>]}
[0m16:57:58.154322 [info ] [MainThread]: 
[0m16:57:58.154997 [info ] [MainThread]: Concurrency: 200 threads (target='dev')
[0m16:57:58.155553 [info ] [MainThread]: 
[0m16:57:58.156287 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m16:57:58.160876 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:57:58.174727 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:57:58.242801 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:57:58.243219 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:57:58.243548 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:57:58.243808 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:57:58.244043 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:57:58.244268 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:57:58.761537 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.517 seconds
[0m16:57:58.772254 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.528 seconds
[0m16:57:58.775906 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPULSE)
[0m16:57:58.776602 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPULSE"
"
[0m16:57:58.778735 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPERFMGT)
[0m16:57:58.779519 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPERFMGT"
"
[0m16:57:58.782525 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPULSE"
[0m16:57:58.784062 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPERFMGT"
[0m16:57:58.784546 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPULSE: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPULSE"} */
create schema if not exists EXPOSE_DEV.dpulse_DPULSE
[0m16:57:58.784902 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPERFMGT: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPERFMGT"} */
create schema if not exists EXPOSE_DEV.dpulse_DPERFMGT
[0m16:57:58.867375 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d21-0106-a02b-0000-03a97fbbe15e
[0m16:57:58.867935 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:57:58.868479 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:57:58.868813 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:57:58.870717 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d21-0106-9fbc-0000-03a97fbbd24e
[0m16:57:58.871044 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:57:58.871397 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:57:58.871667 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:57:58.872475 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:57:58.872816 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPULSE' was left open.
[0m16:57:58.873106 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPULSE: Close
[0m16:57:58.950152 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPERFMGT' was left open.
[0m16:57:58.951044 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPERFMGT: Close
[0m16:57:59.114023 [info ] [MainThread]: 
[0m16:57:59.116054 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.96 seconds (0.96s).
[0m16:57:59.118254 [error] [MainThread]: Encountered an error:
Database Error
  003001 (42501): Erreur de contrôle d'accès SQL :
  privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m16:57:59.120509 [debug] [MainThread]: Command `dbt run` failed at 16:57:59.120272 after 2.10 seconds
[0m16:57:59.121142 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D84821CC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D81CD3D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015D84665FD0>]}
[0m16:57:59.121733 [debug] [MainThread]: Flushing usage events
[0m16:57:59.181250 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:02:53.243803 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4CDC7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4DADA490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4E007D90>]}


============================== 17:02:53.257324 | a0024278-9d54-456d-89e3-0a24447fb946 ==============================
[0m17:02:53.257324 [info ] [MainThread]: Running with dbt=1.10.1
[0m17:02:53.259300 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select crm_deal_quote_relevant', 'send_anonymous_usage_stats': 'True'}
[0m17:02:53.759184 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'a0024278-9d54-456d-89e3-0a24447fb946', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4D4DAFD0>]}
[0m17:02:53.816320 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'a0024278-9d54-456d-89e3-0a24447fb946', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4FF118C0>]}
[0m17:02:53.817502 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m17:02:54.045636 [debug] [MainThread]: checksum: 2c026f85d539c10c69b093157526ce33d0bf5533489eafb07fe5172434ec7740, vars: {}, profile: , target: , version: 1.10.1
[0m17:02:54.234478 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m17:02:54.234916 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m17:02:54.267221 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'a0024278-9d54-456d-89e3-0a24447fb946', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B50398B50>]}
[0m17:02:54.326635 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\manifest.json
[0m17:02:54.331151 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\semantic_manifest.json
[0m17:02:54.352967 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'a0024278-9d54-456d-89e3-0a24447fb946', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4CDCBA70>]}
[0m17:02:54.353474 [info ] [MainThread]: Found 2 models, 477 macros
[0m17:02:54.354144 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'a0024278-9d54-456d-89e3-0a24447fb946', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4FFB9FD0>]}
[0m17:02:54.355520 [info ] [MainThread]: 
[0m17:02:54.356227 [info ] [MainThread]: Concurrency: 200 threads (target='dev')
[0m17:02:54.356833 [info ] [MainThread]: 
[0m17:02:54.357638 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m17:02:54.358710 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m17:02:54.474727 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m17:02:54.475284 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m17:02:54.475663 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m17:02:55.065448 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.590 seconds
[0m17:02:55.070807 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_dpulse_DPULSE)
[0m17:02:55.071696 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "dpulse_DPULSE"
"
[0m17:02:55.078007 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_dpulse_DPULSE"
[0m17:02:55.078555 [debug] [ThreadPool]: On create_EXPOSE_DEV_dpulse_DPULSE: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "GLOBAL_PERFMGT", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_dpulse_DPULSE"} */
create schema if not exists EXPOSE_DEV.dpulse_DPULSE
[0m17:02:55.208598 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd1d26-0106-9fbc-0000-03a97fbc101e
[0m17:02:55.209354 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): Erreur de contrôle d'accès SQL :
privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m17:02:55.210086 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m17:02:55.210585 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m17:02:55.212702 [debug] [MainThread]: Connection 'master' was properly closed.
[0m17:02:55.213366 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_dpulse_DPULSE' was left open.
[0m17:02:55.213879 [debug] [MainThread]: On create_EXPOSE_DEV_dpulse_DPULSE: Close
[0m17:02:55.308940 [info ] [MainThread]: 
[0m17:02:55.310234 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.95 seconds (0.95s).
[0m17:02:55.311728 [error] [MainThread]: Encountered an error:
Database Error
  003001 (42501): Erreur de contrôle d'accès SQL :
  privilèges insuffisants pour effectuer des opérations sur database « EXPOSE_DEV »
[0m17:02:55.313695 [debug] [MainThread]: Command `dbt run` failed at 17:02:55.313469 after 2.50 seconds
[0m17:02:55.314385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B509DBEE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B4DDE3D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B509B2E10>]}
[0m17:02:55.315034 [debug] [MainThread]: Flushing usage events
[0m17:02:55.658023 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:03:28.381386 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C043FA270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C0534FED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C050916D0>]}


============================== 17:03:28.388247 | d6f81a2b-d46d-48a7-9b9d-7a9234f4856f ==============================
[0m17:03:28.388247 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:03:28.389399 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:03:28.510769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd6f81a2b-d46d-48a7-9b9d-7a9234f4856f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C04AA0D60>]}
[0m17:03:28.550258 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m17:03:28.552341 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m17:03:28.553592 [debug] [MainThread]: Command `cli deps` succeeded at 17:03:28.553299 after 0.53 seconds
[0m17:03:28.555240 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C053B3F00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C056E07C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020C053BF950>]}
[0m17:03:28.555652 [debug] [MainThread]: Flushing usage events
[0m17:03:28.659838 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:03:43.899106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002783E57A270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002783F4CFED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002783F20D6D0>]}


============================== 17:03:43.905398 | 33f67839-1671-4ea3-94e1-15b782339b0e ==============================
[0m17:03:43.905398 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:03:43.906117 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m17:03:44.320543 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '33f67839-1671-4ea3-94e1-15b782339b0e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002783EC20D60>]}
[0m17:03:44.367765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '33f67839-1671-4ea3-94e1-15b782339b0e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278416D47C0>]}
[0m17:03:44.368780 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m17:03:44.586012 [debug] [MainThread]: checksum: 53ed91fada2233efb98368d1716b44ab532c83a9c293cf1890b7905d5b45fb25, vars: {}, profile: , target: dev, version: 1.9.4
[0m17:03:44.728564 [info ] [MainThread]: Unable to do partial parsing because config vars, config profile, or config target have changed
[0m17:03:44.729662 [debug] [MainThread]: previous checksum: 53ed91fada2233efb98368d1716b44ab532c83a9c293cf1890b7905d5b45fb25, current checksum: b5597158181700c50f5bc1c71fe28b37a6fb85633dc5323885263678b6bc782c
[0m17:03:44.730096 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '33f67839-1671-4ea3-94e1-15b782339b0e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278419A8850>]}
[0m17:03:45.486941 [warn ] [MainThread]: [[33mWARNING[0m]: Did not find matching node for patch with name 'CRM_DEAL_QUOTE_RELEVANT' in the 'models' section of file 'models\DPULSE\schema.yml'
[0m17:03:45.570596 [warn ] [MainThread]: [[33mWARNING[0m]: Test 'test.GLOBAL_PERFMGT.unique_CRM_DEAL_QUOTE_RELEVANT_opportunityid.cb346feb1b' (models\DPULSE\schema.yml) depends on a node named 'CRM_DEAL_QUOTE_RELEVANT' in package '' which was not found
[0m17:03:45.571173 [warn ] [MainThread]: [[33mWARNING[0m]: Test 'test.GLOBAL_PERFMGT.not_null_CRM_DEAL_QUOTE_RELEVANT_opportunityid.98ccdb2521' (models\DPULSE\schema.yml) depends on a node named 'CRM_DEAL_QUOTE_RELEVANT' in package '' which was not found
[0m17:03:45.633709 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '33f67839-1671-4ea3-94e1-15b782339b0e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027841934AA0>]}
[0m17:03:45.692032 [debug] [MainThread]: Wrote artifact WritableManifest to c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\manifest.json
[0m17:03:45.696706 [debug] [MainThread]: Wrote artifact SemanticManifest to c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\semantic_manifest.json
[0m17:03:45.721692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '33f67839-1671-4ea3-94e1-15b782339b0e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027841CD5FD0>]}
[0m17:03:45.722443 [info ] [MainThread]: Found 2 models, 477 macros
[0m17:03:45.722974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '33f67839-1671-4ea3-94e1-15b782339b0e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027841B33A00>]}
[0m17:03:45.723758 [warn ] [MainThread]: The selection criterion 'dbt_project.yml+' does not match any enabled nodes
[0m17:03:45.725054 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m17:03:45.725593 [debug] [MainThread]: Command end result
[0m17:03:45.745815 [debug] [MainThread]: Wrote artifact WritableManifest to c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\manifest.json
[0m17:03:45.749907 [debug] [MainThread]: Wrote artifact SemanticManifest to c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\semantic_manifest.json
[0m17:03:45.754730 [debug] [MainThread]: Wrote artifact RunExecutionResult to c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\target\run_results.json
[0m17:03:45.755884 [debug] [MainThread]: Command `cli run` succeeded at 17:03:45.755710 after 2.14 seconds
[0m17:03:45.756413 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002783F4BB650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027841D3DE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027841D3D650>]}
[0m17:03:45.756915 [debug] [MainThread]: Flushing usage events
[0m17:03:45.852361 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:59:02.349158 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E611A270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E705FED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E6D9D6D0>]}


============================== 21:59:02.358205 | a789415a-89eb-482f-8112-390b48ab8bd1 ==============================
[0m21:59:02.358205 [info ] [MainThread]: Running with dbt=1.9.4
[0m21:59:02.358908 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt ', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:59:02.438556 [error] [MainThread]: Encountered an error:
Runtime Error
  at path ['name']: 'snfk-dbt' does not match '^[^\\d\\W]\\w*$'

Error encountered in c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml
[0m21:59:02.439604 [debug] [MainThread]: Command `cli deps` failed at 21:59:02.439468 after 0.36 seconds
[0m21:59:02.439996 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E7315CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E7332E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234E70C3CE0>]}
[0m21:59:02.440435 [debug] [MainThread]: Flushing usage events
[0m21:59:02.854842 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:06:55.510808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EFF847620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E8060A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E80B37D90>]}


============================== 22:06:55.515486 | f5d310eb-fe34-4b1e-bea3-e1691d86c4d2 ==============================
[0m22:06:55.515486 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:06:55.516788 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select crm_deal_quote_relevant', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:06:55.520490 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:06:55.521730 [debug] [MainThread]: Command `dbt run` failed at 22:06:55.521587 after 0.24 seconds
[0m22:06:55.522119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E80B61F30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E80BA4CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E80A4D150>]}
[0m22:06:55.522478 [debug] [MainThread]: Flushing usage events
[0m22:06:55.629042 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:07:42.949839 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002039F137620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002039FE3A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203A0367D90>]}


============================== 22:07:42.955538 | f031c830-7880-442f-9060-3dce47df14bf ==============================
[0m22:07:42.955538 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:07:42.956700 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run --select crm_deal_quote_relevant', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:07:42.960220 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:07:42.961820 [debug] [MainThread]: Command `dbt run` failed at 22:07:42.961611 after 0.24 seconds
[0m22:07:42.962375 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203A0391F30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203A03D4CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000203A027D150>]}
[0m22:07:42.962981 [debug] [MainThread]: Flushing usage events
[0m22:07:43.351047 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:08:27.775081 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001839E627620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001839F32A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001839F857D90>]}


============================== 22:08:27.782957 | 7d59f7cd-de76-4223-9e68-5140adbcd1b6 ==============================
[0m22:08:27.782957 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:08:27.784617 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select crm_deal_quote_relevant', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:08:27.788576 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:08:27.789737 [debug] [MainThread]: Command `dbt run` failed at 22:08:27.789523 after 0.23 seconds
[0m22:08:27.790371 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001839F881F30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001839F8C4CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001839F76D150>]}
[0m22:08:27.790809 [debug] [MainThread]: Flushing usage events
[0m22:08:27.891123 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:10:25.652950 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231A8407620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231A911A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231A9647D90>]}


============================== 22:10:25.661018 | dde1fa6d-2045-4ae7-9100-d0d7e18323a8 ==============================
[0m22:10:25.661018 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:10:25.662729 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --target dev --select crm_deal_quote_relevant', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:10:25.668167 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:10:25.670368 [debug] [MainThread]: Command `dbt run` failed at 22:10:25.670013 after 0.31 seconds
[0m22:10:25.671462 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231A9671F30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231A96B4CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231A955D150>]}
[0m22:10:25.672373 [debug] [MainThread]: Flushing usage events
[0m22:10:26.029884 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:11:19.803364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D547B6270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D556FFED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D5543D6D0>]}


============================== 22:11:19.807897 | 88944586-eab6-4cfb-873a-6354dce0f4ed ==============================
[0m22:11:19.807897 [info ] [MainThread]: Running with dbt=1.9.4
[0m22:11:19.808423 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m22:11:19.857650 [error] [MainThread]: Encountered an error:
Runtime Error
  at path ['name']: 'snfk-dbt' does not match '^[^\\d\\W]\\w*$'

Error encountered in c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml
[0m22:11:19.858464 [debug] [MainThread]: Command `cli deps` failed at 22:11:19.858337 after 0.29 seconds
[0m22:11:19.858838 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D559B5CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D559D2E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D55767CE0>]}
[0m22:11:19.859225 [debug] [MainThread]: Flushing usage events
[0m22:11:19.945747 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:31:41.177921 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025AD8487620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025AD9196490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025AD96AFC50>]}


============================== 22:31:41.186796 | 41a0edd4-ba77-42d6-96e1-6eb808657f3e ==============================
[0m22:31:41.186796 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:31:41.188310 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --target dev --select crm_deal_quote_relevant', 'send_anonymous_usage_stats': 'True'}
[0m22:31:41.192660 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:31:41.194551 [debug] [MainThread]: Command `dbt run` failed at 22:31:41.194321 after 0.28 seconds
[0m22:31:41.195042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025AD96E95B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025AD95979B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025AD96248D0>]}
[0m22:31:41.195669 [debug] [MainThread]: Flushing usage events
[0m22:31:41.274155 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:33:35.061081 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0E09E7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0E16F6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0E1C0FC50>]}


============================== 22:33:35.067439 | e6774e25-f1f3-4338-b401-91d2e479f345 ==============================
[0m22:33:35.067439 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:33:35.068899 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --target dev', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:33:35.073845 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:33:35.075679 [debug] [MainThread]: Command `dbt run` failed at 22:33:35.075496 after 0.34 seconds
[0m22:33:35.076749 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0E1C4D5B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0E1AF79B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0E1B848D0>]}
[0m22:33:35.077227 [debug] [MainThread]: Flushing usage events
[0m22:33:35.472586 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:39:24.259173 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE3C27620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE4926490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE4E3FC50>]}


============================== 22:39:24.267331 | 5fbd5285-ffeb-4421-87c1-1746e3e999d4 ==============================
[0m22:39:24.267331 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:39:24.268922 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run --target dev', 'send_anonymous_usage_stats': 'True'}
[0m22:39:24.272445 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'snfk-dbt'
[0m22:39:24.274404 [debug] [MainThread]: Command `dbt run` failed at 22:39:24.274129 after 0.42 seconds
[0m22:39:24.274759 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE4E795B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE4D279B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE4DB48D0>]}
[0m22:39:24.275124 [debug] [MainThread]: Flushing usage events
[0m22:39:24.696231 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:40:04.413647 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB25A7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB32B6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB37CFC50>]}


============================== 22:40:04.417759 | 71616183-395b-4a83-a2bb-469fba115c84 ==============================
[0m22:40:04.417759 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:40:04.418817 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run --target dev', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:40:04.736134 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "snfk-dbt", target "dev" invalid: 20250093 is not valid under any of the given schemas
[0m22:40:04.737771 [debug] [MainThread]: Command `dbt run` failed at 22:40:04.737635 after 0.55 seconds
[0m22:40:04.738131 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB586C180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB5864EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB57F0F30>]}
[0m22:40:04.738517 [debug] [MainThread]: Flushing usage events
[0m22:40:05.062446 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:42:49.105975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024A26D27620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024A27A26490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024A27F3FC50>]}


============================== 22:42:49.115689 | ebaa1277-c51a-4a56-936d-6c1ecf505ad4 ==============================
[0m22:42:49.115689 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:42:49.117450 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --target dev --select crm_deal_quote_relevant', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:42:49.435265 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "snfk-dbt", target "dev" invalid: 20250093 is not valid under any of the given schemas
[0m22:42:49.436840 [debug] [MainThread]: Command `dbt run` failed at 22:42:49.436605 after 0.57 seconds
[0m22:42:49.437272 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024A29EE8180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024A29EE4EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024A29E74F30>]}
[0m22:42:49.437677 [debug] [MainThread]: Flushing usage events
[0m22:42:49.780435 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:45:55.519750 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E18AD7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E197D6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E19CEFC50>]}


============================== 22:45:55.523834 | 4b82dc74-04cb-4d0c-ab8e-8f0b03c4b478 ==============================
[0m22:45:55.523834 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:45:55.524677 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:45:55.825728 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "snfk-dbt", target "dev" invalid: 20250093 is not valid under any of the given schemas
[0m22:45:55.827355 [debug] [MainThread]: Command `dbt test` failed at 22:45:55.827196 after 0.64 seconds
[0m22:45:55.827770 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E1BD28180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E1BD24EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020E1BCB0F30>]}
[0m22:45:55.828168 [debug] [MainThread]: Flushing usage events
[0m22:45:56.240808 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:48:17.142645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C248DF7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C249AF6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C24A00FC50>]}


============================== 22:48:17.151226 | f2ee42ee-6c4c-4c20-b5d3-d969f1474422 ==============================
[0m22:48:17.151226 [info ] [MainThread]: Running with dbt=1.10.1
[0m22:48:17.152858 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --target dev --select crm_deal_quote_relevant', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:48:17.455988 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "snfk-dbt", target "dev" invalid: 20250093 is not valid under any of the given schemas
[0m22:48:17.457490 [debug] [MainThread]: Command `dbt run` failed at 22:48:17.457328 after 0.63 seconds
[0m22:48:17.457897 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C24BF9C180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C24BF94EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C24BF08F30>]}
[0m22:48:17.458318 [debug] [MainThread]: Flushing usage events
[0m22:48:17.846188 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:59:56.842321 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221F65DF4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221F72DA490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221F77EBED0>]}


============================== 08:59:56.855035 | a95ae153-0e42-46cf-94e0-25fc89a1634c ==============================
[0m08:59:56.855035 [info ] [MainThread]: Running with dbt=1.10.1
[0m08:59:56.856388 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:59:56.915752 [error] [MainThread]: Encountered an error:
Runtime Error
  at path ['name']: 'snfk-dbt' does not match '^[^\\d\\W]\\w*$'

Error encountered in c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml
[0m08:59:56.916752 [debug] [MainThread]: Command `cli deps` failed at 08:59:56.916432 after 0.34 seconds
[0m08:59:56.917379 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221F8D54770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221F78D8950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221F7878D10>]}
[0m08:59:56.917694 [debug] [MainThread]: Flushing usage events
[0m08:59:57.266464 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:24:37.197462 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000220DFEAF4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000220E0BBA490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000220E10CFED0>]}


============================== 09:24:37.208900 | 6657ea7c-2711-4e54-8a8b-c317362e82c5 ==============================
[0m09:24:37.208900 [info ] [MainThread]: Running with dbt=1.10.1
[0m09:24:37.210118 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt ', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:24:37.656712 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "snfk-dbt", target "dev" invalid: 20250093 is not valid under any of the given schemas
[0m09:24:37.659887 [debug] [MainThread]: Command `cli run` failed at 09:24:37.659364 after 0.94 seconds
[0m09:24:37.661334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000220E3057E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000220E30E4EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000220E3068E20>]}
[0m09:24:37.662131 [debug] [MainThread]: Flushing usage events
[0m09:24:37.968629 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:48:36.866456 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A3CD6FF4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A3CE40A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A3CE91FED0>]}


============================== 15:48:36.875163 | 586248a7-885a-467a-a8bb-08111bb1a788 ==============================
[0m15:48:36.875163 [info ] [MainThread]: Running with dbt=1.10.1
[0m15:48:36.875795 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m15:48:36.942022 [error] [MainThread]: Encountered an error:
Runtime Error
  at path ['name']: 'snfk-dbt' does not match '^[^\\d\\W]\\w*$'

Error encountered in c:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml
[0m15:48:36.942917 [debug] [MainThread]: Command `cli deps` failed at 15:48:36.942793 after 0.36 seconds
[0m15:48:36.943669 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A3CEF54770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A3CEA08950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A3CE9A8D10>]}
[0m15:48:36.944105 [debug] [MainThread]: Flushing usage events
[0m15:48:37.260127 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:00:58.481836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014950FA7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014951CA6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000149521BFC50>]}


============================== 16:00:58.487915 | 65cefaa6-eb61-4567-a23c-5eb9dcde7492 ==============================
[0m16:00:58.487915 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:00:58.489209 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run --select test_view', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:00:58.790542 [error] [MainThread]: Encountered an error:
Runtime Error
  at path ['name']: 'snfk-dbt' does not match '^[^\\d\\W]\\w*$'

Error encountered in C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml
[0m16:00:58.792042 [debug] [MainThread]: Command `dbt run` failed at 16:00:58.791912 after 0.56 seconds
[0m16:00:58.792342 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014954197360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000149541AE330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000149540DD480>]}
[0m16:00:58.792698 [debug] [MainThread]: Flushing usage events
[0m16:00:59.131892 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:02:25.403517 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3A4E7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3B1F6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3B70FC50>]}


============================== 16:02:25.409017 | 333caecc-72d9-41c9-b1ee-e9ec22d14620 ==============================
[0m16:02:25.409017 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:02:25.410148 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk-dbt\\logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:02:25.425067 [info ] [MainThread]: dbt version: 1.10.1
[0m16:02:25.426592 [info ] [MainThread]: python version: 3.13.3
[0m16:02:25.427214 [info ] [MainThread]: python path: C:\Users\alban.homo\dev\snfk-dbt\.venv\scripts\python.exe
[0m16:02:25.427738 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:02:25.682506 [info ] [MainThread]: Using profiles dir at C:\Users\alban.homo\.dbt
[0m16:02:25.683123 [info ] [MainThread]: Using profiles.yml file at C:\Users\alban.homo\.dbt\profiles.yml
[0m16:02:25.683639 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml
[0m16:02:25.684673 [info ] [MainThread]: adapter type: snowflake
[0m16:02:25.685125 [info ] [MainThread]: adapter version: 1.9.4
[0m16:02:25.736902 [info ] [MainThread]: Configuration:
[0m16:02:25.737680 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:02:25.738223 [info ] [MainThread]:   dbt_project.yml file [[31mERROR invalid[0m]
[0m16:02:25.738612 [info ] [MainThread]: Required dependencies:
[0m16:02:25.738988 [debug] [MainThread]: Executing "git --help"
[0m16:02:25.821439 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:02:25.821879 [debug] [MainThread]: STDERR: "b''"
[0m16:02:25.822200 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:02:25.822729 [info ] [MainThread]: Connection:
[0m16:02:25.823172 [info ] [MainThread]:   account: URW-URW
[0m16:02:25.823619 [info ] [MainThread]:   user: SVC_EUTALEND_DEV
[0m16:02:25.823988 [info ] [MainThread]:   database: EXPOSE_DEV
[0m16:02:25.824338 [info ] [MainThread]:   warehouse: EUINTEG
[0m16:02:25.824640 [info ] [MainThread]:   role: RUSER_SVC_EUTALEND_DEV
[0m16:02:25.825031 [info ] [MainThread]:   schema: DPULSE
[0m16:02:25.825433 [info ] [MainThread]:   authenticator: username_password_mfa
[0m16:02:25.825795 [info ] [MainThread]:   oauth_client_id: None
[0m16:02:25.826188 [info ] [MainThread]:   query_tag: dbt
[0m16:02:25.826580 [info ] [MainThread]:   client_session_keep_alive: False
[0m16:02:25.826896 [info ] [MainThread]:   host: None
[0m16:02:25.827223 [info ] [MainThread]:   port: None
[0m16:02:25.827577 [info ] [MainThread]:   proxy_host: None
[0m16:02:25.827960 [info ] [MainThread]:   proxy_port: None
[0m16:02:25.828304 [info ] [MainThread]:   protocol: None
[0m16:02:25.828670 [info ] [MainThread]:   connect_retries: 1
[0m16:02:25.829078 [info ] [MainThread]:   connect_timeout: None
[0m16:02:25.829500 [info ] [MainThread]:   retry_on_database_errors: False
[0m16:02:25.829876 [info ] [MainThread]:   retry_all: False
[0m16:02:25.830231 [info ] [MainThread]:   insecure_mode: False
[0m16:02:25.830632 [info ] [MainThread]:   reuse_connections: True
[0m16:02:25.831257 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m16:02:26.027631 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m16:02:26.116639 [debug] [MainThread]: Using snowflake connection "debug"
[0m16:02:26.116964 [debug] [MainThread]: On debug: select 1 as id
[0m16:02:26.117178 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:02:26.770717 [debug] [MainThread]: SQL status: SUCCESS 1 in 0.653 seconds
[0m16:02:26.772399 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m16:02:26.773908 [info ] [MainThread]: [31m1 check failed:[0m
[0m16:02:26.775146 [info ] [MainThread]: Project loading failed for the following reason:
Runtime Error
  at path ['name']: 'snfk-dbt' does not match '^[^\\d\\W]\\w*$'

Error encountered in C:\Users\alban.homo\dev\snfk-dbt\snfk-dbt\dbt_project.yml


[0m16:02:26.776907 [debug] [MainThread]: Command `dbt debug` failed at 16:02:26.776710 after 1.64 seconds
[0m16:02:26.777393 [debug] [MainThread]: Connection 'debug' was left open.
[0m16:02:26.777825 [debug] [MainThread]: On debug: Close
[0m16:02:26.865738 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3DE21810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3DD07650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD3D65B9B0>]}
[0m16:02:26.866877 [debug] [MainThread]: Flushing usage events
[0m16:02:26.978106 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:06:46.773117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1D08F4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1DD8A490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1E29BED0>]}


============================== 16:06:46.777528 | dcf1df54-4600-4929-ac0f-9aaf3770cd02 ==============================
[0m16:06:46.777528 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:06:46.778013 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk_dbt\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:06:46.876566 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'dcf1df54-4600-4929-ac0f-9aaf3770cd02', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1D792D70>]}
[0m16:06:46.900052 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m16:06:46.901695 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m16:06:46.902782 [debug] [MainThread]: Command `cli deps` succeeded at 16:06:46.902660 after 0.38 seconds
[0m16:06:46.903190 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1E3296A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1E3286B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019D1E331150>]}
[0m16:06:46.903467 [debug] [MainThread]: Flushing usage events
[0m16:06:47.314111 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:07:46.197228 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023520DC7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023521AC6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023521FDFC50>]}


============================== 16:07:46.206015 | 2f39e9ba-9b04-4288-9420-2fc0129964b6 ==============================
[0m16:07:46.206015 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:07:46.207531 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk_dbt\\logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m16:07:46.231365 [info ] [MainThread]: dbt version: 1.10.1
[0m16:07:46.232112 [info ] [MainThread]: python version: 3.13.3
[0m16:07:46.232647 [info ] [MainThread]: python path: C:\Users\alban.homo\dev\snfk-dbt\.venv\scripts\python.exe
[0m16:07:46.233038 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m16:07:46.526402 [info ] [MainThread]: Using profiles dir at C:\Users\alban.homo\.dbt
[0m16:07:46.527108 [info ] [MainThread]: Using profiles.yml file at C:\Users\alban.homo\.dbt\profiles.yml
[0m16:07:46.527576 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\alban.homo\dev\snfk-dbt\snfk_dbt\dbt_project.yml
[0m16:07:46.528475 [info ] [MainThread]: adapter type: snowflake
[0m16:07:46.528907 [info ] [MainThread]: adapter version: 1.9.4
[0m16:07:46.615281 [info ] [MainThread]: Configuration:
[0m16:07:46.616581 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:07:46.617255 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m16:07:46.617674 [info ] [MainThread]: Required dependencies:
[0m16:07:46.618246 [debug] [MainThread]: Executing "git --help"
[0m16:07:46.705860 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:07:46.706240 [debug] [MainThread]: STDERR: "b''"
[0m16:07:46.706532 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:07:46.707070 [info ] [MainThread]: Connection:
[0m16:07:46.707450 [info ] [MainThread]:   account: URW-URW
[0m16:07:46.707772 [info ] [MainThread]:   user: SVC_EUTALEND_DEV
[0m16:07:46.708124 [info ] [MainThread]:   database: EXPOSE_DEV
[0m16:07:46.708443 [info ] [MainThread]:   warehouse: EUINTEG
[0m16:07:46.708775 [info ] [MainThread]:   role: RUSER_SVC_EUTALEND_DEV
[0m16:07:46.709086 [info ] [MainThread]:   schema: DPULSE
[0m16:07:46.709376 [info ] [MainThread]:   authenticator: username_password_mfa
[0m16:07:46.709672 [info ] [MainThread]:   oauth_client_id: None
[0m16:07:46.709950 [info ] [MainThread]:   query_tag: dbt
[0m16:07:46.710241 [info ] [MainThread]:   client_session_keep_alive: False
[0m16:07:46.710550 [info ] [MainThread]:   host: None
[0m16:07:46.710848 [info ] [MainThread]:   port: None
[0m16:07:46.711134 [info ] [MainThread]:   proxy_host: None
[0m16:07:46.711443 [info ] [MainThread]:   proxy_port: None
[0m16:07:46.711741 [info ] [MainThread]:   protocol: None
[0m16:07:46.712024 [info ] [MainThread]:   connect_retries: 1
[0m16:07:46.712355 [info ] [MainThread]:   connect_timeout: None
[0m16:07:46.712672 [info ] [MainThread]:   retry_on_database_errors: False
[0m16:07:46.712979 [info ] [MainThread]:   retry_all: False
[0m16:07:46.713331 [info ] [MainThread]:   insecure_mode: False
[0m16:07:46.713750 [info ] [MainThread]:   reuse_connections: True
[0m16:07:46.714256 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m16:07:46.873417 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m16:07:46.938608 [debug] [MainThread]: Using snowflake connection "debug"
[0m16:07:46.938886 [debug] [MainThread]: On debug: select 1 as id
[0m16:07:46.939068 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:07:47.565590 [debug] [MainThread]: SQL status: SUCCESS 1 in 0.626 seconds
[0m16:07:47.566387 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m16:07:47.567092 [info ] [MainThread]: [32mAll checks passed![0m
[0m16:07:47.567805 [debug] [MainThread]: Command `dbt debug` succeeded at 16:07:47.567724 after 1.59 seconds
[0m16:07:47.568023 [debug] [MainThread]: Connection 'debug' was left open.
[0m16:07:47.568214 [debug] [MainThread]: On debug: Close
[0m16:07:47.638894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023524615940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023520E8A450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023523F1B9B0>]}
[0m16:07:47.639951 [debug] [MainThread]: Flushing usage events
[0m16:07:47.954741 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:07:56.574425 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA2AE7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA37E6490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA3CFFC50>]}


============================== 16:07:56.579357 | 6c2d0e61-8d6f-44fb-b4b5-d5cd5716e47a ==============================
[0m16:07:56.579357 [info ] [MainThread]: Running with dbt=1.10.1
[0m16:07:56.580513 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk-dbt\\snfk_dbt\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --select test_view', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:07:56.911340 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '6c2d0e61-8d6f-44fb-b4b5-d5cd5716e47a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA31EEFD0>]}
[0m16:07:56.951772 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '6c2d0e61-8d6f-44fb-b4b5-d5cd5716e47a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA5D55040>]}
[0m16:07:56.952682 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m16:07:57.121793 [debug] [MainThread]: checksum: 2c026f85d539c10c69b093157526ce33d0bf5533489eafb07fe5172434ec7740, vars: {}, profile: , target: , version: 1.10.1
[0m16:07:57.271065 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m16:07:57.271362 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m16:07:57.293755 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '6c2d0e61-8d6f-44fb-b4b5-d5cd5716e47a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA6084050>]}
[0m16:07:57.336422 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk_dbt\target\manifest.json
[0m16:07:57.358043 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk-dbt\snfk_dbt\target\semantic_manifest.json
[0m16:07:57.375548 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '6c2d0e61-8d6f-44fb-b4b5-d5cd5716e47a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA2AEFA70>]}
[0m16:07:57.375986 [info ] [MainThread]: Found 3 models, 477 macros
[0m16:07:57.376554 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '6c2d0e61-8d6f-44fb-b4b5-d5cd5716e47a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA5DC3D90>]}
[0m16:07:57.377690 [info ] [MainThread]: 
[0m16:07:57.378096 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m16:07:57.378530 [info ] [MainThread]: 
[0m16:07:57.378995 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m16:07:57.380166 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m16:07:57.463925 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m16:07:57.464256 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "snfk_dbt", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m16:07:57.464463 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:07:58.145109 [debug] [ThreadPool]: SQL status: SUCCESS 54 in 0.680 seconds
[0m16:07:58.149632 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_DPULSE_DPULSE)
[0m16:07:58.150523 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "DPULSE_DPULSE"
"
[0m16:07:58.155931 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_DPULSE_DPULSE"
[0m16:07:58.156279 [debug] [ThreadPool]: On create_EXPOSE_DEV_DPULSE_DPULSE: /* {"app": "dbt", "dbt_version": "1.10.1", "profile_name": "snfk_dbt", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_DPULSE_DPULSE"} */
create schema if not exists EXPOSE_DEV.DPULSE_DPULSE
[0m16:07:58.269941 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bd228f-0106-a33f-0000-03a97fe88202
[0m16:07:58.270366 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'EXPOSE_DEV'
[0m16:07:58.270744 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m16:07:58.271011 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m16:07:58.271868 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:07:58.272208 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_DPULSE_DPULSE' was left open.
[0m16:07:58.272447 [debug] [MainThread]: On create_EXPOSE_DEV_DPULSE_DPULSE: Close
[0m16:07:58.354079 [info ] [MainThread]: 
[0m16:07:58.356038 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.98 seconds (0.98s).
[0m16:07:58.357358 [error] [MainThread]: Encountered an error:
Database Error
  003001 (42501): SQL access control error:
  Insufficient privileges to operate on database 'EXPOSE_DEV'
[0m16:07:58.359154 [debug] [MainThread]: Command `dbt run` failed at 16:07:58.358960 after 2.02 seconds
[0m16:07:58.359715 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA685BE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA3ACF650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011AA680A210>]}
[0m16:07:58.360253 [debug] [MainThread]: Flushing usage events
[0m16:07:58.422072 [debug] [MainThread]: An error was encountered while trying to flush usage events
