dbt-fusion 2.0.0-preview.6
   Loading ~/.dbt/profiles.yml
 Debugging profile: dev
 Debugging dbt version: 2.0.0-preview.6
 Debugging platform: windows x86_64 (windows)
 Debugging adapter type: snowflake (remote)
 Debugging dependencies:
  git: OK
 Debugging connection:
  "schema": "DPULSE",
  "database": "EXPOSE_DEV",
  "role": "RUSER_ALBANHOMO",
  "user": "20250093",
  "account": "URW-URW",
  "warehouse": "EUGENERIC"
 Debugging connection test: OK
  Debugged All checks passed!
  Finished 'debug' target 'dev' in 9s 629ms
[0m18:44:01.973633 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 18:44:02.181225 | 8576957a-bbf2-4549-88ea-77d8ddfc230c ==============================
[0m18:44:02.181225 [info ] [MainThread]: Running with dbt=1.10.2
[0m18:44:02.182287 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt deps', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'printer_width': '80', 'empty': 'None', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt'}
[0m18:44:02.420586 [debug] [MainThread]: Set downloads directory='C:\Users\ALBAN~1.HOM\AppData\Local\Temp\dbt-downloads-r697ujf3'
[0m18:44:02.421087 [info ] [MainThread]: Installing https://github.com/dbt-labs/dbt-utils.git
[0m18:44:02.421577 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt-utils.git b03949bb53de3439f6a8057088ba4032"
[0m18:44:03.618472 [debug] [MainThread]: STDOUT: "b''"
[0m18:44:03.619036 [debug] [MainThread]: STDERR: "b"Cloning into 'b03949bb53de3439f6a8057088ba4032'...\n""
[0m18:44:03.619555 [debug] [MainThread]: Pulling new dependency b03949bb53de3439f6a8057088ba4032.
[0m18:44:03.619955 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m18:44:03.713560 [debug] [MainThread]: STDOUT: "b'0feb9571187119dc48203ad91d8b064a660d6d3a\n'"
[0m18:44:03.713887 [debug] [MainThread]: STDERR: "b''"
[0m18:44:03.714195 [debug] [MainThread]: Checking out revision e164c645238ca98f21b2ecc558912b94b3d75a9f.
[0m18:44:03.714430 [debug] [MainThread]: Executing "git fetch origin --depth 1 e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m18:44:04.894257 [debug] [MainThread]: STDOUT: "b''"
[0m18:44:04.894583 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt-utils\n * branch            e164c645238ca98f21b2ecc558912b94b3d75a9f -> FETCH_HEAD\n'"
[0m18:44:04.894802 [debug] [MainThread]: Executing "git reset --hard e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m18:44:05.056462 [debug] [MainThread]: STDOUT: "b'HEAD is now at e164c64 Update changelog for 1.3.0 (#943)\n'"
[0m18:44:05.056774 [debug] [MainThread]: STDERR: "b''"
[0m18:44:05.056993 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m18:44:05.143096 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m18:44:05.143412 [debug] [MainThread]: STDERR: "b''"
[0m18:44:05.143688 [debug] [MainThread]: Checked out at e164c64.
[0m18:44:05.143894 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m18:44:05.219284 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m18:44:05.219607 [debug] [MainThread]: STDERR: "b''"
[0m18:44:05.220477 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt-utils.git b03949bb53de3439f6a8057088ba4032"
[0m18:44:05.301046 [debug] [MainThread]: STDOUT: "b''"
[0m18:44:05.301372 [debug] [MainThread]: STDERR: "b"fatal: destination path 'b03949bb53de3439f6a8057088ba4032' already exists and is not an empty directory.\n""
[0m18:44:05.301621 [debug] [MainThread]: command return code=128
[0m18:44:05.302063 [debug] [MainThread]: Updating existing dependency b03949bb53de3439f6a8057088ba4032.
[0m18:44:05.302251 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m18:44:05.377157 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m18:44:05.377488 [debug] [MainThread]: STDERR: "b''"
[0m18:44:05.377769 [debug] [MainThread]: Checking out revision e164c645238ca98f21b2ecc558912b94b3d75a9f.
[0m18:44:05.377971 [debug] [MainThread]: Executing "git fetch origin --depth 1 e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m18:44:06.284345 [debug] [MainThread]: STDOUT: "b''"
[0m18:44:06.284654 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt-utils\n * branch            e164c645238ca98f21b2ecc558912b94b3d75a9f -> FETCH_HEAD\n'"
[0m18:44:06.284874 [debug] [MainThread]: Executing "git reset --hard e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m18:44:06.369732 [debug] [MainThread]: STDOUT: "b'HEAD is now at e164c64 Update changelog for 1.3.0 (#943)\n'"
[0m18:44:06.370069 [debug] [MainThread]: STDERR: "b''"
[0m18:44:06.370451 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m18:44:06.442333 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m18:44:06.442654 [debug] [MainThread]: STDERR: "b''"
[0m18:44:06.442937 [debug] [MainThread]: Already at e164c64, nothing to do.
[0m18:44:06.445095 [info ] [MainThread]: Installed from revision e164c645238ca98f21b2ecc558912b94b3d75a9f
[0m18:44:06.446444 [debug] [MainThread]: Command `dbt deps` succeeded at 18:44:06.446310 after 4.51 seconds
[0m18:44:06.446800 [debug] [MainThread]: Flushing usage events
[0m18:58:11.440202 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 18:58:11.705635 | 5c4a5487-57d3-4113-ab9e-65c14ec7b217 ==============================
[0m18:58:11.705635 [info ] [MainThread]: Running with dbt=1.10.2
[0m18:58:11.707221 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt run --select crm_leasingorderproduct.sql', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m18:58:12.330234 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m18:58:12.558725 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m18:58:12.716631 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m18:58:13.713839 [error] [MainThread]: Encountered an error:
Compilation Error in model V_DIM_PC_PERFORMANCE_GLOBAL (models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql)
  'dbt.adapters.contracts.relation.Path object' has no attribute 'split'
[0m18:58:13.715553 [debug] [MainThread]: Command `dbt run` failed at 18:58:13.715444 after 2.31 seconds
[0m18:58:13.715824 [debug] [MainThread]: Flushing usage events
[0m18:58:31.034032 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 18:58:31.254220 | 5fd58ccd-3681-4be6-bf2d-660d4cdf41b0 ==============================
[0m18:58:31.254220 [info ] [MainThread]: Running with dbt=1.10.2
[0m18:58:31.255255 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'False', 'quiet': 'False', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt'}
[0m18:58:31.689930 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m18:58:31.869769 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m18:58:32.023141 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m18:58:32.942424 [error] [MainThread]: Encountered an error:
Compilation Error in model V_DIM_PC_PERFORMANCE_GLOBAL (models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql)
  'dbt.adapters.contracts.relation.Path object' has no attribute 'split'
[0m18:58:32.943749 [debug] [MainThread]: Command `dbt run` failed at 18:58:32.943643 after 1.95 seconds
[0m18:58:32.944056 [debug] [MainThread]: Flushing usage events
[0m18:59:28.175258 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 18:59:28.397450 | 30f9a494-f4e6-4faa-97cf-e06b7200cc4f ==============================
[0m18:59:28.397450 [info ] [MainThread]: Running with dbt=1.10.2
[0m18:59:28.398984 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'False', 'quiet': 'False', 'printer_width': '80', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m18:59:28.829830 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m18:59:28.999688 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m18:59:29.148786 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m18:59:30.065398 [error] [MainThread]: Encountered an error:
Compilation Error in model V_DIM_PC_PERFORMANCE_GLOBAL (models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql)
  'dbt.adapters.contracts.relation.Path object' has no attribute 'split'
[0m18:59:30.066315 [debug] [MainThread]: Command `dbt run` failed at 18:59:30.066206 after 1.93 seconds
[0m18:59:30.066564 [debug] [MainThread]: Flushing usage events
[0m19:00:09.294512 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:00:09.494253 | 9b25acef-b27e-4ea0-9f8a-ba248bc2010e ==============================
[0m19:00:09.494253 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:00:09.495050 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'log_cache_events': 'False', 'empty': 'False', 'use_experimental_parser': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m19:00:09.935157 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:00:10.112175 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:00:10.265382 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:00:11.213881 [error] [MainThread]: Encountered an error:
Compilation Error in model V_DIM_PC_PERFORMANCE_GLOBAL (models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql)
  'dbt.adapters.contracts.relation.Path object' has no attribute 'split'
[0m19:00:11.214635 [debug] [MainThread]: Command `dbt run` failed at 19:00:11.214530 after 1.96 seconds
[0m19:00:11.214941 [debug] [MainThread]: Flushing usage events
[0m19:01:53.494855 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:01:53.731266 | 4e408ddf-c055-421d-8220-7267ad86675b ==============================
[0m19:01:53.731266 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:01:53.732478 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'empty': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m19:01:54.223621 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:01:54.405970 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:01:54.559500 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:01:55.574499 [error] [MainThread]: Encountered an error:
Compilation Error in model V_DIM_PC_PERFORMANCE_GLOBAL (models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql)
  access to attribute '__str__' of 'Path' object is unsafe.
[0m19:01:55.575403 [debug] [MainThread]: Command `dbt run` failed at 19:01:55.575300 after 2.12 seconds
[0m19:01:55.575661 [debug] [MainThread]: Flushing usage events
[0m19:03:54.776868 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:03:55.000185 | cfd42e90-a541-45a6-81f1-aae549b88c5f ==============================
[0m19:03:55.000185 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:03:55.000889 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'empty': 'False', 'printer_width': '80', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m19:03:55.446371 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:03:55.615067 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:03:55.767038 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:03:56.052439 [error] [MainThread]: Encountered an error:
Compilation Error
  Reached EOF without finding a close tag for macro (searched from line 1)
[0m19:03:56.053481 [debug] [MainThread]: Command `dbt run` failed at 19:03:56.053363 after 1.31 seconds
[0m19:03:56.053748 [debug] [MainThread]: Flushing usage events
[0m19:04:11.505706 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:04:11.741056 | 9837d4d7-6309-4150-a8f8-e58a580f2e16 ==============================
[0m19:04:11.741056 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:04:11.742134 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'empty': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m19:04:12.167843 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:04:12.335166 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:04:12.501625 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:04:12.785406 [error] [MainThread]: Encountered an error:
Compilation Error
  Reached EOF without finding a close tag for macro (searched from line 1)
[0m19:04:12.786233 [debug] [MainThread]: Command `dbt run` failed at 19:04:12.786096 after 1.32 seconds
[0m19:04:12.786509 [debug] [MainThread]: Flushing usage events
[0m19:04:41.798352 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:04:42.014685 | 4090c8fd-51a5-47a4-903d-259a1952994f ==============================
[0m19:04:42.014685 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:04:42.015376 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'False', 'log_cache_events': 'False', 'quiet': 'False', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m19:04:42.451409 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:04:42.622253 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:04:42.775245 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:04:43.064718 [error] [MainThread]: Encountered an error:
Compilation Error
  Reached EOF without finding a close tag for macro (searched from line 1)
[0m19:04:43.065623 [debug] [MainThread]: Command `dbt run` failed at 19:04:43.065523 after 1.30 seconds
[0m19:04:43.065876 [debug] [MainThread]: Flushing usage events
[0m19:05:29.493020 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:05:29.703908 | 6edeb4be-7ca2-48da-b024-13d93c0a6307 ==============================
[0m19:05:29.703908 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:05:29.704938 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'empty': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt'}
[0m19:05:30.139120 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:05:30.308269 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:05:30.461692 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:05:31.380238 [error] [MainThread]: Encountered an error:
Compilation Error in model V_DIM_PC_PERFORMANCE_GLOBAL (models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql)
  'str' is undefined
[0m19:05:31.381140 [debug] [MainThread]: Command `dbt run` failed at 19:05:31.381039 after 1.92 seconds
[0m19:05:31.381390 [debug] [MainThread]: Flushing usage events
[0m19:06:40.750325 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:06:40.969901 | f74f69e1-d4f9-49bf-8476-6bd1f1bed146 ==============================
[0m19:06:40.969901 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:06:40.970638 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'empty': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m19:06:41.401370 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:06:41.572277 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:06:41.727940 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m19:06:45.116515 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk_dbt\snfk_urw\target\manifest.json
[0m19:06:45.121402 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk_dbt\snfk_urw\target\semantic_manifest.json
[0m19:06:45.204190 [info ] [MainThread]: Found 35 models, 2 data tests, 423 sources, 614 macros
[0m19:06:45.209764 [info ] [MainThread]: 
[0m19:06:45.210391 [info ] [MainThread]: Concurrency: 200 threads (target='dev')
[0m19:06:45.211196 [info ] [MainThread]: 
[0m19:06:45.211895 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m19:06:45.213950 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m19:06:45.329740 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m19:06:45.330055 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "snfk_urw", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m19:06:45.330265 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m19:06:46.280630 [debug] [ThreadPool]: SQL status: SUCCESS 55 in 0.950 seconds
[0m19:06:46.284478 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL'))
[0m19:06:46.285310 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "DPULSE_Path(database=\'EXPOSE_DEV\', schema=\'DPULSE\', identifier=\'V_DIM_PC_PERFORMANCE_GLOBAL\')"
"
[0m19:06:46.291805 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')"
[0m19:06:46.292450 [debug] [ThreadPool]: On create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL'): /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "snfk_urw", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')"} */
create schema if not exists EXPOSE_DEV.DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')
[0m19:06:46.458690 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bea762-0207-165c-0000-03a98b4802aa
[0m19:06:46.459302 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 001003 (42000): Erreur de compilation SQL :
ligne d'erreur de syntaxe 1 à la position 50, « ( » inattendu.
[0m19:06:46.459882 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m19:06:46.460309 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m19:06:46.461587 [debug] [MainThread]: Connection 'master' was properly closed.
[0m19:06:46.462133 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')' was left open.
[0m19:06:46.462590 [debug] [MainThread]: On create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL'): Close
[0m19:06:46.542949 [info ] [MainThread]: 
[0m19:06:46.543966 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.33 seconds (1.33s).
[0m19:06:46.544523 [error] [MainThread]: Encountered an error:
Database Error
  001003 (42000): Erreur de compilation SQL :
  ligne d'erreur de syntaxe 1 à la position 50, « ( » inattendu.
[0m19:06:46.545624 [debug] [MainThread]: Command `dbt run` failed at 19:06:46.545446 after 5.83 seconds
[0m19:06:46.546094 [debug] [MainThread]: Flushing usage events
[0m19:10:59.171557 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 19:10:59.424059 | fd72447a-1ad9-4988-bd47-da3b5136a157 ==============================
[0m19:10:59.424059 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:10:59.425049 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt run --select V_DIM_PC_PERFORMANCE_GLOBAL.sql', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'empty': 'False', 'log_cache_events': 'False', 'quiet': 'False', 'log_path': 'C:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt'}
[0m19:10:59.847764 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m19:11:00.037728 [debug] [MainThread]: checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
[0m19:11:00.256283 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 2 files changed.
[0m19:11:00.257118 [debug] [MainThread]: Partial parsing: updated file: URW://models\Expose\DPERFMGT\V_DIM_PC_PERFORMANCE_GLOBAL.sql
[0m19:11:00.257416 [debug] [MainThread]: Partial parsing: updated file: URW://macros\get_schema.sql
[0m19:11:00.379493 [info ] [MainThread]: Schema folder: Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')
[0m19:11:00.986041 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\alban.homo\dev\snfk_dbt\snfk_urw\target\manifest.json
[0m19:11:00.991011 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\alban.homo\dev\snfk_dbt\snfk_urw\target\semantic_manifest.json
[0m19:11:01.066603 [info ] [MainThread]: Found 35 models, 2 data tests, 423 sources, 614 macros
[0m19:11:01.074739 [info ] [MainThread]: 
[0m19:11:01.075602 [info ] [MainThread]: Concurrency: 200 threads (target='dev')
[0m19:11:01.076312 [info ] [MainThread]: 
[0m19:11:01.077092 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m19:11:01.078289 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_EXPOSE_DEV'
[0m19:11:01.160266 [debug] [ThreadPool]: Using snowflake connection "list_EXPOSE_DEV"
[0m19:11:01.160569 [debug] [ThreadPool]: On list_EXPOSE_DEV: /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "snfk_urw", "target_name": "dev", "connection_name": "list_EXPOSE_DEV"} */
show terse schemas in database EXPOSE_DEV
    limit 10000
[0m19:11:01.160769 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m19:11:01.780782 [debug] [ThreadPool]: SQL status: SUCCESS 55 in 0.620 seconds
[0m19:11:01.785540 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_EXPOSE_DEV, now create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL'))
[0m19:11:01.786460 [debug] [ThreadPool]: Creating schema "database: "EXPOSE_DEV"
schema: "DPULSE_Path(database=\'EXPOSE_DEV\', schema=\'DPULSE\', identifier=\'V_DIM_PC_PERFORMANCE_GLOBAL\')"
"
[0m19:11:01.792046 [debug] [ThreadPool]: Using snowflake connection "create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')"
[0m19:11:01.792457 [debug] [ThreadPool]: On create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL'): /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "snfk_urw", "target_name": "dev", "connection_name": "create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')"} */
create schema if not exists EXPOSE_DEV.DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')
[0m19:11:01.887878 [debug] [ThreadPool]: Snowflake adapter: Snowflake query id: 01bea767-0207-1661-0000-03a98b48207e
[0m19:11:01.888473 [debug] [ThreadPool]: Snowflake adapter: Snowflake error: 001003 (42000): Erreur de compilation SQL :
ligne d'erreur de syntaxe 1 à la position 50, « ( » inattendu.
[0m19:11:01.889053 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro create_schema
[0m19:11:01.889524 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m19:11:01.890984 [debug] [MainThread]: Connection 'master' was properly closed.
[0m19:11:01.891441 [debug] [MainThread]: Connection 'create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL')' was left open.
[0m19:11:01.891811 [debug] [MainThread]: On create_EXPOSE_DEV_DPULSE_Path(database='EXPOSE_DEV', schema='DPULSE', identifier='V_DIM_PC_PERFORMANCE_GLOBAL'): Close
[0m19:11:01.976581 [info ] [MainThread]: 
[0m19:11:01.978205 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.90 seconds (0.90s).
[0m19:11:01.979639 [error] [MainThread]: Encountered an error:
Database Error
  001003 (42000): Erreur de compilation SQL :
  ligne d'erreur de syntaxe 1 à la position 50, « ( » inattendu.
[0m19:11:01.980385 [debug] [MainThread]: Command `dbt run` failed at 19:11:01.980279 after 2.84 seconds
[0m19:11:01.980670 [debug] [MainThread]: Flushing usage events
[0m15:28:05.660398 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 15:28:05.878722 | c20c43cd-6e3f-4df8-96ba-512813a7401a ==============================
[0m15:28:05.878722 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:28:05.879847 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt ', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'printer_width': '80', 'log_path': 'c:\\Users\\alban.homo\\dev\\snfk_dbt\\snfk_urw\\logs', 'indirect_selection': 'eager', 'profiles_dir': 'C:\\Users\\alban.homo\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m15:28:06.164559 [debug] [MainThread]: Set downloads directory='C:\Users\ALBAN~1.HOM\AppData\Local\Temp\dbt-downloads-oz6j3qzv'
[0m15:28:06.165310 [info ] [MainThread]: Installing https://github.com/dbt-labs/dbt-utils.git
[0m15:28:06.165991 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt-utils.git b03949bb53de3439f6a8057088ba4032"
[0m15:28:07.748546 [debug] [MainThread]: STDOUT: "b''"
[0m15:28:07.748912 [debug] [MainThread]: STDERR: "b"Cloning into 'b03949bb53de3439f6a8057088ba4032'...\n""
[0m15:28:07.749225 [debug] [MainThread]: Pulling new dependency b03949bb53de3439f6a8057088ba4032.
[0m15:28:07.749428 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m15:28:07.843896 [debug] [MainThread]: STDOUT: "b'7672637704c7ae428125d8aa1769e5e34ae32251\n'"
[0m15:28:07.844255 [debug] [MainThread]: STDERR: "b''"
[0m15:28:07.844560 [debug] [MainThread]: Checking out revision e164c645238ca98f21b2ecc558912b94b3d75a9f.
[0m15:28:07.844766 [debug] [MainThread]: Executing "git fetch origin --depth 1 e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m15:28:09.054222 [debug] [MainThread]: STDOUT: "b''"
[0m15:28:09.054582 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt-utils\n * branch            e164c645238ca98f21b2ecc558912b94b3d75a9f -> FETCH_HEAD\n'"
[0m15:28:09.054825 [debug] [MainThread]: Executing "git reset --hard e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m15:28:09.226600 [debug] [MainThread]: STDOUT: "b'HEAD is now at e164c64 Update changelog for 1.3.0 (#943)\n'"
[0m15:28:09.226962 [debug] [MainThread]: STDERR: "b''"
[0m15:28:09.227189 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m15:28:09.318364 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m15:28:09.318718 [debug] [MainThread]: STDERR: "b''"
[0m15:28:09.319031 [debug] [MainThread]: Checked out at e164c64.
[0m15:28:09.319244 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m15:28:09.414883 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m15:28:09.415233 [debug] [MainThread]: STDERR: "b''"
[0m15:28:09.416189 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt-utils.git b03949bb53de3439f6a8057088ba4032"
[0m15:28:09.507618 [debug] [MainThread]: STDOUT: "b''"
[0m15:28:09.507978 [debug] [MainThread]: STDERR: "b"fatal: destination path 'b03949bb53de3439f6a8057088ba4032' already exists and is not an empty directory.\n""
[0m15:28:09.508182 [debug] [MainThread]: command return code=128
[0m15:28:09.508585 [debug] [MainThread]: Updating existing dependency b03949bb53de3439f6a8057088ba4032.
[0m15:28:09.508782 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m15:28:09.595391 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m15:28:09.595753 [debug] [MainThread]: STDERR: "b''"
[0m15:28:09.596055 [debug] [MainThread]: Checking out revision e164c645238ca98f21b2ecc558912b94b3d75a9f.
[0m15:28:09.596260 [debug] [MainThread]: Executing "git fetch origin --depth 1 e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m15:28:10.586564 [debug] [MainThread]: STDOUT: "b''"
[0m15:28:10.586939 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt-utils\n * branch            e164c645238ca98f21b2ecc558912b94b3d75a9f -> FETCH_HEAD\n'"
[0m15:28:10.587272 [debug] [MainThread]: Executing "git reset --hard e164c645238ca98f21b2ecc558912b94b3d75a9f"
[0m15:28:10.704285 [debug] [MainThread]: STDOUT: "b'HEAD is now at e164c64 Update changelog for 1.3.0 (#943)\n'"
[0m15:28:10.704872 [debug] [MainThread]: STDERR: "b''"
[0m15:28:10.705346 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m15:28:10.798567 [debug] [MainThread]: STDOUT: "b'e164c645238ca98f21b2ecc558912b94b3d75a9f\n'"
[0m15:28:10.798919 [debug] [MainThread]: STDERR: "b''"
[0m15:28:10.799216 [debug] [MainThread]: Already at e164c64, nothing to do.
[0m15:28:10.801539 [info ] [MainThread]: Installed from revision e164c645238ca98f21b2ecc558912b94b3d75a9f
[0m15:28:10.803011 [debug] [MainThread]: Command `cli deps` succeeded at 15:28:10.802854 after 5.19 seconds
[0m15:28:10.803359 [debug] [MainThread]: Flushing usage events
